let Countries = [
    "Argentina",
    "Australia",
    "Austria",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Bhutan",
    "Brazil",
    "British Virgin Islands",
    "Denmark",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "Finland",
    "France",
    "Germany",
    "India",
    "Japan",
    "Malaysia",
    "Maldives",
    "Mexico",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Russia",
    "Saudi Arabia",
    "Singapore",
    "South Africa",
    "South Korea",
    "Spain",
    "Sri Lanka",
    "Sweden",
    "Switzerland",
    "Taiwan",
    "Thailand",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Venezuela",
    "Vietnam",
];

export default Countries;